config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#dashboard'

  get 'home/dashboard' => 'home#dashboard'

  get 'home/report' => 'home#report'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_filter :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action -> { get_tweets params}
  def dashboard
    if params[:tweet]
      @no_of_unique_users = @tweet_user.flatten.uniq.count
      @no_of_tweets = @tweets.flatten.compact.count || 0
      @no_of_retweets = @retweets.flatten.compact.count || 0
    end
  end

  def report
    if params[:tweet_date]
      @tweet_by_date = @tweet_results.map{|tweet| tweet if tweet["created_at"].to_date.strftime("%Y-%m-%d") == params[:tweet_date]}.compact
    end
  end

  private
  def get_tweets(params)
    if params[:tweet]
      path = "https://api.twitter.com/1.1/search/tweets.json?q=#{params[:tweet]}&result_type=popular"
      api_helper = ApiHelper.new(current_user)
      @tweet_results = api_helper.call_method('get', path)
      @tweets = []
      @tweet_user = []
      @retweets = []
      @tweet_results.map do |tweet|
        @tweet_user << tweet["user"]["id"]
        @tweets << tweet["text"]
        @retweets << tweet["retweeted_status"]["text"] if tweet["retweeted"]
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_report_listing.html.erb
<%if !params[:tweet_date].blank?%>
  <table>
    <h4>Tweet by date</h4>
    <% if @tweet_by_date %>
      <% @tweet_by_date.each do |tweet| %>
        <tr>
          <td><%= tweet["text"] %></td>
        </tr>
      <% end %>
    <% end%>
  </table>
<%elsif !params[:retweet].blank?%>
  <table>
    <h4>Retweets</h4>
    <% if @retweets %>
      <% @retweets.each do |retweet| %>
        <tr>
          <td><%= retweet %></td>
        </tr>
      <% end %>
    <% end%>
  </table>
<%else%>
  <table>
    <h4>Tweets</h4>
    <% if @tweets %>
      <% @tweets.each do |tweet| %>
        <tr>
          <td><%= tweet %></td>
        </tr>
      <% end %>
    <% end%>
  </table>
<%end%>

app/views/home/dashboard.html.erb
<div class="dash-bdy">
  <div class = "container">
    <div class="form-div">
      <div class="row">
        <div class="col-lg-3">
          <%= form_tag home_dashboard_path, method: :get do %>
            <%= label_tag 'Enter a keyword'%>
            <%= text_field_tag :tweet %>
            <%= submit_tag 'Search' %>
          <% end %>
        </div>
        <div class="col-lg-9">
          <% if params[:tweet] %>
            <table class='table-trd'>
              <tr>
                <td>Number of unique users tweeting the same keyword: </td>
                <td><%= @no_of_unique_users %></td>
              </tr>
              <tr>
                <td>Number of tweets: </td>
                <td><%= @no_of_tweets %></td>
              </tr>
              <tr>
                <td>Number of retweets: </td>
                <td><%= @no_of_retweets %></td>
              </tr>
            </table>
          <%end%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/report.html.erb
<div class="dash-bdy">
  <div class="report">
    <table>
      <tr>
        <%= form_tag(home_report_path, method: :get) do %>
          <h4>Filter by:</h4>
          <%= select_tag(:filter, options_for_select([['Tweet', 1],['Retweet', 2], ['Date of tweet', 3]], selected: params[:filter]), prompt: 'Select option') %>
          <td>
            <div id="twet">
              <%= label_tag "Tweet"%>
              <%= text_field_tag :tweet, params[:tweet] %>
            </div>
            <div id="retwet">
              <%= label_tag "Retweet"%>
              <%= text_field_tag :retweet, params[:retweet] %>
            </div>
            <div id="twet_date">
              <%= label_tag "Tweet by Date"%>
              <%= date_field_tag :tweet_date %>
            </div>
          </td>
          <td>
            <%= submit_tag 'Search'%>
          </td>
        <%end%>
      </tr>
    </table>
    <%= render 'report_listing'%>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwitterSearch</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
</head>
<% if user_signed_in? %>
  <header class="navbar navbar-static-top bs-docs-nav" id="top" role="banner">
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Twitter</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li><%= link_to 'Dashboard', home_dashboard_path %></li>
              <li><%= link_to 'Report', home_report_path(tweet: params[:tweet]) %></li>
              <li><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </header>
<%end%>

<body>

<%= yield %>

</body>
</html>